// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var LaunchdarklyNodeServerSdk = require("launchdarkly-node-server-sdk");

var ldclient = LaunchdarklyNodeServerSdk.init("sdk-64fb3f87-7e48-4a8d-99de-595a7472472f");

ldclient.on("ready", (function (param) {
        console.log("It's now safe to request feature flags");
        var showFeature = ldclient.variation("my-first-feature-flag", false);
        if (showFeature) {
          console.log("Show feature");
        } else {
          console.log("Don't show feature");
        }
        
      }));

exports.ldclient = ldclient;
/* ldclient Not a pure module */
